name: The Hyperx Organization CI
run-name: Deploy to The Hyperx Organization
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute Composite Action
        uses: ./.github/actions/compose-one
        with:
          greeting: "Hello"
          name: "TheHyperX"